apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "content.fullname" . }}-config
  labels: {{- include "content.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{- if ne (toString $v) "" }}
  {{ $k }}: {{ toString $v | quote }}
  {{- end }}
  {{- end }}
