"""Who the caller is, and who owns a row.

Two words for two questions, and keeping them apart is what makes the rest of
the code readable:

``user_id``
    Who is making this request. Established once, at the edge, by
    :func:`content.api.auth.current_user`. Never declared by the client — the
    client sends a secret, the server derives the identity (ADR 0030).

``owner_id``
    Who a stored row or a stored file belongs to. In an ordinary request they
    are the same value; they are not the same *concept*, and an operator route
    that lists someone else's jobs is exactly where the difference shows.

``LOCAL_OWNER`` is the single implicit user of a self-hosted instance. It is
not a fallback, an anonymous marker, or a guest: it is a real owner id that
simply never had to sign in. Everything else in the codebase can then assume
an owner exists, always — there is no "no user" branch anywhere.

Chosen over ``default`` (which reads as "a default value" and could collide
with a real account named default) and over ``self_hosted`` (which names a
deployment mode, not a person). Real accounts get ``usr_<random>`` ids, so
``local`` can never collide with one.
"""

from enum import Enum

LOCAL_OWNER = "local"


class AuthMode(str, Enum):
    """How ``current_user`` establishes identity.

    ``none`` is the default and keeps the historical behaviour exactly: no
    credential is asked for, every request belongs to :data:`LOCAL_OWNER`.
    This is the self-hosted contract of ADR 0024, unchanged.

    ``token`` is the hosted contract: a request without a valid credential is
    rejected, and the owner comes from the credential.
    """

    NONE = "none"
    TOKEN = "token"


def is_valid_owner_id(value: str) -> bool:
    """A cheap shape check, used where an owner id crosses a boundary.

    Owner ids become path segments on disk, so they must never contain a
    separator or a traversal sequence. This is belt-and-braces: ids are
    generated by the engine, never by a client.
    """
    if not value or len(value) > 64:
        return False
    if value in {".", ".."}:
        return False
    return all(c.isalnum() or c in {"_", "-"} for c in value)
